/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ChangeImpactRouteImport } from './routes/change-impact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DepartmentRouteImport } from './routes/department'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as GrievancesRouteImport } from './routes/grievances'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RegulatoryMapRouteImport } from './routes/regulatory-map'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DepartmentIndexRouteImport } from './routes/department/index'
import { Route as DepartmentApplicationsRouteImport } from './routes/department/applications'
import { Route as DepartmentAuditRouteImport } from './routes/department/audit'
import { Route as DepartmentBottlenecksRouteImport } from './routes/department/bottlenecks'
import { Route as DepartmentGrievancesRouteImport } from './routes/department/grievances'
import { Route as DepartmentOfficersRouteImport } from './routes/department/officers'
import { Route as DepartmentSettingsRouteImport } from './routes/department/settings'
import { Route as DepartmentSlaRouteImport } from './routes/department/sla'
import { Route as DepartmentApplicationAppIdRouteImport } from './routes/department/application.$appId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeImpactRoute = ChangeImpactRouteImport.update({
  id: '/change-impact',
  path: '/change-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentRoute = DepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievancesRoute = GrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryMapRoute = RegulatoryMapRouteImport.update({
  id: '/regulatory-map',
  path: '/regulatory-map',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentIndexRoute = DepartmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepartmentRoute,
} as any)
const DepartmentApplicationsRoute = DepartmentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DepartmentRoute,
} as any)
const DepartmentAuditRoute = DepartmentAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DepartmentRoute,
} as any)
const DepartmentBottlenecksRoute = DepartmentBottlenecksRouteImport.update({
  id: '/bottlenecks',
  path: '/bottlenecks',
  getParentRoute: () => DepartmentRoute,
} as any)
const DepartmentGrievancesRoute = DepartmentGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => DepartmentRoute,
} as any)
const DepartmentOfficersRoute = DepartmentOfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => DepartmentRoute,
} as any)
const DepartmentSettingsRoute = DepartmentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DepartmentRoute,
} as any)
const DepartmentSlaRoute = DepartmentSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => DepartmentRoute,
} as any)
const DepartmentApplicationAppIdRoute =
  DepartmentApplicationAppIdRouteImport.update({
    id: '/application/$appId',
    path: '/application/$appId',
    getParentRoute: () => DepartmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/change-impact': typeof ChangeImpactRoute
  '/compliance': typeof ComplianceRoute
  '/department': typeof DepartmentRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/evaluation': typeof EvaluationRoute
  '/grievances': typeof GrievancesRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/regulatory-map': typeof RegulatoryMapRoute
  '/requirements': typeof RequirementsRoute
  '/schemes': typeof SchemesRoute
  '/sources': typeof SourcesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/department/applications': typeof DepartmentApplicationsRoute
  '/department/audit': typeof DepartmentAuditRoute
  '/department/bottlenecks': typeof DepartmentBottlenecksRoute
  '/department/grievances': typeof DepartmentGrievancesRoute
  '/department/officers': typeof DepartmentOfficersRoute
  '/department/settings': typeof DepartmentSettingsRoute
  '/department/sla': typeof DepartmentSlaRoute
  '/department/': typeof DepartmentIndexRoute
  '/department/application/$appId': typeof DepartmentApplicationAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/change-impact': typeof ChangeImpactRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/evaluation': typeof EvaluationRoute
  '/grievances': typeof GrievancesRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/regulatory-map': typeof RegulatoryMapRoute
  '/requirements': typeof RequirementsRoute
  '/schemes': typeof SchemesRoute
  '/sources': typeof SourcesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/department/applications': typeof DepartmentApplicationsRoute
  '/department/audit': typeof DepartmentAuditRoute
  '/department/bottlenecks': typeof DepartmentBottlenecksRoute
  '/department/grievances': typeof DepartmentGrievancesRoute
  '/department/officers': typeof DepartmentOfficersRoute
  '/department/settings': typeof DepartmentSettingsRoute
  '/department/sla': typeof DepartmentSlaRoute
  '/department': typeof DepartmentIndexRoute
  '/department/application/$appId': typeof DepartmentApplicationAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/change-impact': typeof ChangeImpactRoute
  '/compliance': typeof ComplianceRoute
  '/department': typeof DepartmentRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/evaluation': typeof EvaluationRoute
  '/grievances': typeof GrievancesRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/regulatory-map': typeof RegulatoryMapRoute
  '/requirements': typeof RequirementsRoute
  '/schemes': typeof SchemesRoute
  '/sources': typeof SourcesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/department/applications': typeof DepartmentApplicationsRoute
  '/department/audit': typeof DepartmentAuditRoute
  '/department/bottlenecks': typeof DepartmentBottlenecksRoute
  '/department/grievances': typeof DepartmentGrievancesRoute
  '/department/officers': typeof DepartmentOfficersRoute
  '/department/settings': typeof DepartmentSettingsRoute
  '/department/sla': typeof DepartmentSlaRoute
  '/department/': typeof DepartmentIndexRoute
  '/department/application/$appId': typeof DepartmentApplicationAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/change-impact'
    | '/compliance'
    | '/department'
    | '/documents'
    | '/evaluation'
    | '/grievances'
    | '/login'
    | '/projects'
    | '/regulatory-map'
    | '/requirements'
    | '/schemes'
    | '/sources'
    | '/auth/callback'
    | '/department/applications'
    | '/department/audit'
    | '/department/bottlenecks'
    | '/department/grievances'
    | '/department/officers'
    | '/department/settings'
    | '/department/sla'
    | '/department/'
    | '/department/application/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/change-impact'
    | '/compliance'
    | '/documents'
    | '/evaluation'
    | '/grievances'
    | '/login'
    | '/projects'
    | '/regulatory-map'
    | '/requirements'
    | '/schemes'
    | '/sources'
    | '/auth/callback'
    | '/department/applications'
    | '/department/audit'
    | '/department/bottlenecks'
    | '/department/grievances'
    | '/department/officers'
    | '/department/settings'
    | '/department/sla'
    | '/department'
    | '/department/application/$appId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/change-impact'
    | '/compliance'
    | '/department'
    | '/documents'
    | '/evaluation'
    | '/grievances'
    | '/login'
    | '/projects'
    | '/regulatory-map'
    | '/requirements'
    | '/schemes'
    | '/sources'
    | '/auth/callback'
    | '/department/applications'
    | '/department/audit'
    | '/department/bottlenecks'
    | '/department/grievances'
    | '/department/officers'
    | '/department/settings'
    | '/department/sla'
    | '/department/'
    | '/department/application/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ChangeImpactRoute: typeof ChangeImpactRoute
  ComplianceRoute: typeof ComplianceRoute
  DepartmentRoute: typeof DepartmentRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  EvaluationRoute: typeof EvaluationRoute
  GrievancesRoute: typeof GrievancesRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  RegulatoryMapRoute: typeof RegulatoryMapRoute
  RequirementsRoute: typeof RequirementsRoute
  SchemesRoute: typeof SchemesRoute
  SourcesRoute: typeof SourcesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-impact': {
      id: '/change-impact'
      path: '/change-impact'
      fullPath: '/change-impact'
      preLoaderRoute: typeof ChangeImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department': {
      id: '/department'
      path: '/department'
      fullPath: '/department'
      preLoaderRoute: typeof DepartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievances': {
      id: '/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof GrievancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-map': {
      id: '/regulatory-map'
      path: '/regulatory-map'
      fullPath: '/regulatory-map'
      preLoaderRoute: typeof RegulatoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department/': {
      id: '/department/'
      path: '/'
      fullPath: '/department/'
      preLoaderRoute: typeof DepartmentIndexRouteImport
      parentRoute: typeof DepartmentRoute
    }
    '/department/applications': {
      id: '/department/applications'
      path: '/applications'
      fullPath: '/department/applications'
      preLoaderRoute: typeof DepartmentApplicationsRouteImport
      parentRoute: typeof DepartmentRoute
    }
    '/department/audit': {
      id: '/department/audit'
      path: '/audit'
      fullPath: '/department/audit'
      preLoaderRoute: typeof DepartmentAuditRouteImport
      parentRoute: typeof DepartmentRoute
    }
    '/department/bottlenecks': {
      id: '/department/bottlenecks'
      path: '/bottlenecks'
      fullPath: '/department/bottlenecks'
      preLoaderRoute: typeof DepartmentBottlenecksRouteImport
      parentRoute: typeof DepartmentRoute
    }
    '/department/grievances': {
      id: '/department/grievances'
      path: '/grievances'
      fullPath: '/department/grievances'
      preLoaderRoute: typeof DepartmentGrievancesRouteImport
      parentRoute: typeof DepartmentRoute
    }
    '/department/officers': {
      id: '/department/officers'
      path: '/officers'
      fullPath: '/department/officers'
      preLoaderRoute: typeof DepartmentOfficersRouteImport
      parentRoute: typeof DepartmentRoute
    }
    '/department/settings': {
      id: '/department/settings'
      path: '/settings'
      fullPath: '/department/settings'
      preLoaderRoute: typeof DepartmentSettingsRouteImport
      parentRoute: typeof DepartmentRoute
    }
    '/department/sla': {
      id: '/department/sla'
      path: '/sla'
      fullPath: '/department/sla'
      preLoaderRoute: typeof DepartmentSlaRouteImport
      parentRoute: typeof DepartmentRoute
    }
    '/department/application/$appId': {
      id: '/department/application/$appId'
      path: '/application/$appId'
      fullPath: '/department/application/$appId'
      preLoaderRoute: typeof DepartmentApplicationAppIdRouteImport
      parentRoute: typeof DepartmentRoute
    }
  }
}

interface DepartmentRouteChildren {
  DepartmentApplicationsRoute: typeof DepartmentApplicationsRoute
  DepartmentAuditRoute: typeof DepartmentAuditRoute
  DepartmentBottlenecksRoute: typeof DepartmentBottlenecksRoute
  DepartmentGrievancesRoute: typeof DepartmentGrievancesRoute
  DepartmentOfficersRoute: typeof DepartmentOfficersRoute
  DepartmentSettingsRoute: typeof DepartmentSettingsRoute
  DepartmentSlaRoute: typeof DepartmentSlaRoute
  DepartmentIndexRoute: typeof DepartmentIndexRoute
  DepartmentApplicationAppIdRoute: typeof DepartmentApplicationAppIdRoute
}

const DepartmentRouteChildren: DepartmentRouteChildren = {
  DepartmentApplicationsRoute: DepartmentApplicationsRoute,
  DepartmentAuditRoute: DepartmentAuditRoute,
  DepartmentBottlenecksRoute: DepartmentBottlenecksRoute,
  DepartmentGrievancesRoute: DepartmentGrievancesRoute,
  DepartmentOfficersRoute: DepartmentOfficersRoute,
  DepartmentSettingsRoute: DepartmentSettingsRoute,
  DepartmentSlaRoute: DepartmentSlaRoute,
  DepartmentIndexRoute: DepartmentIndexRoute,
  DepartmentApplicationAppIdRoute: DepartmentApplicationAppIdRoute,
}

const DepartmentRouteWithChildren = DepartmentRoute._addFileChildren(
  DepartmentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ChangeImpactRoute: ChangeImpactRoute,
  ComplianceRoute: ComplianceRoute,
  DepartmentRoute: DepartmentRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  EvaluationRoute: EvaluationRoute,
  GrievancesRoute: GrievancesRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  RegulatoryMapRoute: RegulatoryMapRoute,
  RequirementsRoute: RequirementsRoute,
  SchemesRoute: SchemesRoute,
  SourcesRoute: SourcesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
